name: docker-buildx

on:
  push:
    branches:
        - "master"

jobs:
  agentx-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - run: make -f multi.Makefile agentx
      - run: make -f multi.Makefile agentx-docker

  pluginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -f multi.Makefile pluginx
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            out/*